### ISSUE TITLE
Failed to clear temp folder, and how to automate with windows?

### ISSUE THREAD

**Issue by MMJv3** [FreekBes/insta_reddit_bot#8]
The bot fails to clear the temp folder so i have to do it manually, was wondering if there's a fix for that

and how can i automate this on windows? i don't have a Linux machine

**Comment by FreekBes** [comment]
Use the built-in task scheduler. Hit <kbd>windows</kbd> + <kbd>S</kbd> on your keyboard, type _Task Scheduler_ and run the result.

In the sidebar on the right, click "create a task", then on the "triggers" tab you can set up a so-called trigger which runs the bot. Click "new", and in advanced settings you can set "repeat task every" to 5 minutes or so.

I'm not entirely sure how to set up Task Scheduler further than that. Maybe this link might be of help: https://www.windowscentral.com/how-create-automated-task-using-task-scheduler-windows-10

**Comment by MMJv3** [comment]
thank you!

now, do you know of any way to fix clearing the temp folder automatically?

**Comment by FreekBes** [comment]
You have to modify the clearTemp() function in main.js for that. Instead of having exec run the `rf -rf` command, make it run the equivalent command for Windows.

Also, video is not supported on Windows, as ffmpeg is missing. You could try installing it from [here](https://ffmpeg.zeranoe.com/builds/), but I would suggest running the code in a virtual box instead (or, even better, [use the Windows Subsystem for Linux](https://ubuntu.com/tutorials/ubuntu-on-windows), although I'm not sure if cron works there). This would also "fix" the issue for the temp folder.
